### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by davipatricio** [Shibe-Studio/Shynk#5]
** Descreva o bug **
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Passos para reproduzir o comportamento

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

** Contexto adicional **
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Lucaas1** [comment]
Sim, este bug é importante

**Comment by Lucaas1** [comment]
iremos resolver
